apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-boot-java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: java-app
    spec:
      containers:
      - name: spring-boot-container
        image: tharwat3551/demo-java-app:Latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9099
      


