apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring_boot_java_app_deployment
  labels:
    app: java_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java_app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: java_app
    spec:
      containers:
      - name: spring-boot-container
        image: tharwat3551/demo-java-app:Latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9099
      


