apiVersion: v1
kind: Service
metadata:
  name: spring-boot-java-app-service
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 9099
    protocol: TCP
    nodePort: 30036
