apiVersion: v1
kind: Service
metadata:
  name: spring_boot_java_app_service
  labels:
    app: java_app
spec:
  selector:
    app: java_app
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 9099
    protocol: TCP
    nodePort: 30036
